In [1]:
from utils.data_preprocessing import dose_class, load_data, LABEL_KEY

In [9]:
data = load_data()
x = dict(data.iloc[1])
x['enzyme_ind'] = ((x['Carbamazepine (Tegretol)']==1) | (x['Phenytoin (Dilantin)']==1 ) | (x['Rifampin or Rifampicin']==1)).astype(float)
x

{'PharmGKB Subject ID': 'PA135312262',
 'Gender': 'female',
 'Race': 'White',
 'Ethnicity': 'not Hispanic or Latino',
 'Age': '50 - 59',
 'Height (cm)': 176.53,
 'Weight (kg)': 144.2,
 'Indication for Warfarin Treatment': '7',
 'Comorbidities': 'Cancer',
 'Diabetes': nan,
 'Congestive Heart Failure and/or Cardiomyopathy': nan,
 'Valve Replacement': nan,
 'Medications': 'not aspirin; not simvastatin; not amiodarone',
 'Aspirin': 0.0,
 'Acetaminophen or Paracetamol (Tylenol)': nan,
 'Was Dose of Acetaminophen or Paracetamol (Tylenol) >1300mg/day': nan,
 'Simvastatin (Zocor)': 0.0,
 'Atorvastatin (Lipitor)': nan,
 'Fluvastatin (Lescol)': nan,
 'Lovastatin (Mevacor)': nan,
 'Pravastatin (Pravachol)': nan,
 'Rosuvastatin (Crestor)': nan,
 'Cerivastatin (Baycol)': nan,
 'Amiodarone (Cordarone)': 0.0,
 'Carbamazepine (Tegretol)': 0.0,
 'Phenytoin (Dilantin)': 0.0,
 'Rifampin or Rifampicin': 0.0,
 'Sulfonamide Antibiotics': nan,
 'Macrolide Antibiotics': nan,
 'Anti-fungal Azoles': nan,
 'Herb

In [11]:

(4.0376-x['Age in decades']*0.2546+x['Height (cm)']*0.0118+x['Weight (kg)']*0.0134-x['Asian']*0.6752+x['Black']*0.406+x['Unknown race']*0.0443+x['enzyme_ind']*1.2799-x['Amiodarone (Cordarone)']*0.5695)**2

45.96750504435601

In [25]:
np.zeros(len(features)) #, 1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
features = [
    "Age in decades",
    "Height (cm)",
    "Weight (kg)",
    "Male",
    "Female",
    "Asian",
    "Black",
    "White",
    "Unknown race",
    "Carbamazepine (Tegretol)",
    "Phenytoin (Dilantin)",
    "Rifampin or Rifampicin",
    "Amiodarone (Cordarone)",
]
np.array([x[f] for f in features]).reshape([-1,1]).transpose().shape

(1, 13)

In [23]:
!python run.py

In [21]:
!python grader.py

========== START GRADING
----- START 1a-0-basic: test for fixed prediction
----- END 1a-0-basic [took 0:00:00.109785 (max allowed 2 seconds), 0.5/0.5 points]

----- START 1a-1-basic: evaluate the performance of clincal model on a single example
----- END 1a-1-basic [took 0:00:00.111495 (max allowed 2 seconds), 0.5/0.5 points]

----- START 1b-0-basic: basic test for correct initialization
----- END 1b-0-basic [took 0:00:00.109257 (max allowed 2 seconds), 2/2 points]

----- START 1b-1-basic: evaluate the choose function of LinUCB on a single example
----- END 1b-1-basic [took 0:00:00.130728 (max allowed 2 seconds), 2/2 points]

----- START 1c-0-basic: evaluate the choose function of egreedy disjoint linear UCB on single example
----- END 1c-0-basic [took 0:00:00.625042 (max allowed 10 seconds), 4/4 points]

----- START 1d-0-basic: basic test for correct initialization
----- END 1d-0-basic [took 0:00:00.138035 (max allowed 2 seconds), 2/2 points]

----- START 1d-1-basic: basic evaluation 

In [4]:
import numpy as np
np.argmax([1,2,2])

1

In [8]:
mu =np.zeros((5, 1))
mu

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
f = np.zeros(5)

In [9]:
B = np.eye(5)
B_inv = np.linalg.inv(B)
B_inv

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [-0., -0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [14]:
np.matmul(B_inv, f)

array([0., 0., 0., 0., 0.])